/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuadroSlugRouteImport } from './routes/cuadro.$slug'
import { Route as ObraSlugRouteImport } from './routes/obra.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuadroSlugRoute = CuadroSlugRouteImport.update({
  id: '/cuadro/$slug',
  path: '/cuadro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraSlugRoute = ObraSlugRouteImport.update({
  id: '/obra/$slug',
  path: '/obra/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuadro/$slug': typeof CuadroSlugRoute
  '/obra/$slug': typeof ObraSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuadro/$slug': typeof CuadroSlugRoute
  '/obra/$slug': typeof ObraSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuadro/$slug': typeof CuadroSlugRoute
  '/obra/$slug': typeof ObraSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cuadro/$slug' | '/obra/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cuadro/$slug' | '/obra/$slug'
  id: '__root__' | '/' | '/cuadro/$slug' | '/obra/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuadroSlugRoute: typeof CuadroSlugRoute
  ObraSlugRoute: typeof ObraSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuadro/$slug': {
      id: '/cuadro/$slug'
      path: '/cuadro/$slug'
      fullPath: '/cuadro/$slug'
      preLoaderRoute: typeof CuadroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/$slug': {
      id: '/obra/$slug'
      path: '/obra/$slug'
      fullPath: '/obra/$slug'
      preLoaderRoute: typeof ObraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuadroSlugRoute: CuadroSlugRoute,
  ObraSlugRoute: ObraSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
